name = "workflow-orland"
main = "src/index.ts"
compatibility_date = "2024-03-26"

# Cloudflare Assets akan otomatis menyajikan folder public/ (UI Kamu)
assets = { directory = "./public" }

[[d1_databases]]
binding = "DB_SSO"
database_name = "sso_database"
database_id = "6ebafba7-dafb-4e46-a4fe-b73e20ef7e4e"

[vars]
TURNSTILE_SECRET = "0x4AAAAAACs8dTjOU5UcntgtIKPw4lJznNg"
